import { useState, useEffect, useRef } from 'react'
import './App.css'
import { AuthService } from './services/auth'

function App() {
  const [messages, setMessages] = useState<{ role: string; content: string }[]>([
    { role: 'assistant', content: 'Hello! I am GitHub Copilot. How can I help you today?' }
  ])
  const [inputValue, setInputValue] = useState('')
  const [isLoggedIn, setIsLoggedIn] = useState(false)
  const [isLoading, setIsLoading] = useState(true)
  const messagesEndRef = useRef<HTMLDivElement>(null)

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages])

  useEffect(() => {
    const initAuth = async () => {
      let githubToken = AuthService.getGithubToken()
      
      if (!githubToken) {
        try {
          // Try to load from config.json generated by CLI login
          const resp = await fetch('/config.json')
          if (resp.ok) {
            const config = await resp.json()
            if (config.github_token) {
              AuthService.setGithubToken(config.github_token)
              githubToken = config.github_token
              console.log('Loaded GitHub token from config.json')
            }
          }
        } catch (e) {
          // config.json might not exist, which is fine
        }
      }

      if (githubToken) {
        setIsLoggedIn(true)
      }
      setIsLoading(false)
    }
    initAuth()
  }, [])

  useEffect(() => {
    if (!isLoggedIn) return

    let timeoutId: number

    const refreshLoop = async () => {
      const githubToken = AuthService.getGithubToken()
      if (!githubToken) return

      try {
        const data = await AuthService.fetchCopilotToken(githubToken)
        const refreshIn = data.refresh_in || 1500
        const sleepMs = Math.max(refreshIn - 60, 30) * 1000
        console.log(`Next Copilot token refresh in ${sleepMs / 1000}s`)
        timeoutId = window.setTimeout(refreshLoop, sleepMs)
      } catch (error) {
        console.error('Failed to refresh Copilot token:', error)
        // Try again in 30 seconds if failed
        timeoutId = window.setTimeout(refreshLoop, 30000)
      }
    }

    refreshLoop()
    return () => window.clearTimeout(timeoutId)
  }, [isLoggedIn])

  const handleLogin = async () => {
    alert('Browser-based login is restricted by GitHub CORS policies. Please use the CLI to login:\n\nnpm run login\n\nThen refresh this page.')
  }

  const handleLogout = () => {
    localStorage.removeItem('github_token')
    localStorage.removeItem('copilot_token')
    setIsLoggedIn(false)
    setMessages([{ role: 'assistant', content: 'You have been logged out. Please login again to continue.' }])
  }

  const handleSend = async () => {
    if (!inputValue.trim()) return

    // Validate tokens before adding user message
    let copilotToken = AuthService.getCopilotToken()
    const githubToken = AuthService.getGithubToken()

    if (!copilotToken) {
      if (!githubToken) {
        setMessages(prev => [...prev, { role: 'assistant', content: 'Error: Please login with GitHub first.' }])
        return
      }
      try {
        const data = await AuthService.fetchCopilotToken(githubToken)
        copilotToken = data.token
      } catch (err) {
        console.error('Failed to get copilot token:', err)
        setMessages(prev => [...prev, { role: 'assistant', content: 'Error: Your GitHub token might be expired or doesn\'t have Copilot access.' }])
        return
      }
    }

    // We have a valid copilot token, proceed
    const userMessage = { role: 'user', content: inputValue }
    setMessages(prev => [...prev, userMessage])
    setInputValue('')

    try {
      const response = await fetch('https://api.githubcopilot.com/chat/completions', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${copilotToken}`,
          'Content-Type': 'application/json',
          'editor-version': 'vscode/1.85.1',
          'editor-plugin-version': 'copilot/1.155.0',
          'user-agent': 'GithubCopilot/1.155.0',
          'Copilot-Integration-Id': 'vscode-chat',
          'OpenAI-Intent': 'conversation-panel',
          'Accept': 'application/json',
        },
        body: JSON.stringify({
          messages: messages.concat(userMessage).map(m => ({ role: m.role, content: m.content })),
          model: 'gpt-4o',
          stream: false,
        })
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))
        throw new Error(errorData.message || `Copilot API error: ${response.status}`)
      }

      const data = await response.json()
      const assistantMessage = data.choices[0].message
      setMessages(prev => [...prev, assistantMessage])
    } catch (error) {
      console.error('Chat error:', error)
      setMessages(prev => [...prev, { role: 'assistant', content: `Error: ${error instanceof Error ? error.message : 'Unknown error'}` }])
    }
  }

  if (isLoading) {
    return <div className="loading">Loading...</div>
  }

  if (!isLoggedIn) {
    return (
      <div className="login-container">
        <h1 className="login-title">Copilot Chat</h1>
        <p className="login-subtitle">Enterprise Web Edition</p>
        
        <button onClick={handleLogin} className="login-button">
          Login with GitHub
        </button>
      </div>
    )
  }

  return (
    <div className="chat-container">
      <div className="chat-header">
        <span className="chat-title">Copilot Chat</span>
        <button onClick={handleLogout} className="logout-button">Logout</button>
      </div>
      <div className="chat-messages">
        {messages.map((msg, index) => (
          <div key={index} className={`message ${msg.role}`}>
            <div className="message-content">{msg.content}</div>
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>
      <div className="chat-input-area">
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyPress={(e) => e.key === 'Enter' && handleSend()}
          placeholder="Type a message..."
          className="chat-input"
        />
        <button onClick={handleSend} className="send-button">
          Send
        </button>
      </div>
    </div>
  )
}

export default App
